### ISSUE TITLE
No released version works on clang 4. Can we have a release?

### ISSUE THREAD

**Issue by copumpkin** [sandstorm-io/capnproto#433]
I'm using 0.5.3 and very early in the build, I get the following error:

```
clang++ -std=gnu++11 -DHAVE_CONFIG_H -I.    -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR='"/nix/store/nlsxycirl0lph34nb6sxw1108i9fypgy-capnproto-0.5.3/include"' -D_THREAD_SAFE  -O2 -DNDEBUG -D_THREAD_SAFE  -c -o src/capnp/compiler/module-loader.o src/capnp/compiler/module-loader.c++
In file included from src/capnp/compiler/module-loader.c++:22:
In file included from src/capnp/compiler/module-loader.h:29:
In file included from src/capnp/compiler/compiler.h:29:
In file included from ./src/capnp/compiler/grammar.capnp.h:7:
In file included from ./src/capnp/generated-header-support.h:31:
./src/capnp/layout.h:129:65: error: value of type 'bool' is not implicitly convertible to 'capnp::Kind'
template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
```

**Comment by copumpkin** [comment]
Oh, never mind, this was fixed in https://github.com/sandstorm-io/capnproto/pull/399. Can we have a release including that?

**Comment by copumpkin** [comment]
Reopening because I'm asking for a release 😄

**Comment by kentonv** [comment]
A release will probably occur "soon", i.e., within 1-4 weeks.

However I have made that claim a lot of times and then failed to actually do it. :(

But now that I work at Cloudflare which is a big Cap'n Proto user (as opposed to a tiny understaffed startup), it seems more likely that I'll be able to get this done, maybe!

**Comment by copumpkin** [comment]
That'll be awesome, thanks. For now I'm just porting over the patch from #399 onto the 0.5.3 release to get it to build on recent Clang, but I've left a comment saying to remove the patch once we get a new release 😄

**Comment by kentonv** [comment]
Hello,

I just released 0.5.3.1 to fix an obscure security issue (affecting 32-bit MacOS builds only), and I rolled in this fix while I was at it. So, there's now a release that should work, fixing this issue.

Sorry it took so long!

(I'm still working on 0.6 release soon...)

**Comment by copumpkin** [comment]
Lovely, thanks!

**Comment by kentonv** [comment]
Here's the advisory, BTW: https://github.com/sandstorm-io/capnproto/blob/master/security-advisories/2017-04-17-0-apple-clang-elides-bounds-check.md
