### ISSUE TITLE
capnproto 0.5.3 FTBFS on GCC 7 for Fedora 26 (RHBZ#1423291)

### ISSUE THREAD

**Issue by Conan-Kudo** [sandstorm-io/capnproto#418]
During the development of Fedora 26, we've done a mass rebuild in accordance with [the work to switch the distribution to GCC 7](https://fedoraproject.org/wiki/Changes/GCC7).

However, capnproto 0.5.3 fails to build on GCC 7 (gcc 7.0.1).

This is the error that repeats itself throughout the build run, with some variation based on the file in the make thread (run at `make -j48`):
```
In file included from src/capnp/list.h:29:0,
                 from src/capnp/list.c++:22:
src/capnp/layout.h:129:65: error: could not convert template argument 'b' from 'bool' to 'capnp::Kind'
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
                                                                 ^
src/capnp/layout.h:129:66: error: template argument 1 is invalid
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
                                                                  ^~
```
Full build logs are available at the [Red Hat Bugzilla bug](https://bugzilla.redhat.com/show_bug.cgi?id=1423291).

**Comment by Omnifarious** [comment]
I tried using the latest gcc from rawhide, and I didn't get those errors. It built fine. But capnproto crashed.

**Comment by Omnifarious** [comment]
$ ./capnp compile -oc++ src/capnp/test.capnp 
*** Received signal #11: Segmentation fault
stack: 0x7fe469a08b65 0x7fe469a0a2fb 0x7fe469a0b444 0x7fe469a0b444 0x7fe469a0c516 0x4081fd 0x7fe469a57811 0x7fe469a5790b 0x7fe469a57e39 0x7fe469a57e74 0x40c1e8 0x7fe46954770a 0x7fe469548acb 0x7fe46953a988 0x7fe469549445 0x405dc1 0x7fe4686a55fe 0x405e9a

**Comment by kentonv** [comment]
I believed this was fixed in master by 0f1fd1938b19dccdb5dbfe9cb5177c4342a2a5b5. You can cherry-pick that into your package if needed.

**Comment by kentonv** [comment]
@Omnifarious You seem to be describing a separate bug. Could you file a separate issue?
